import 'dart:convert';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:csv/csv.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:henryladmin/constants/colors/app_colors.dart';
import 'package:henryladmin/constants/loader/loader.dart';
import 'package:henryladmin/services/routes/routes.dart';
import 'dart:html' as html;

class ExportToCsv extends StatefulWidget {
  ExportToCsv({Key? key}) : super(key: key);

  @override
  State<ExportToCsv> createState() => _ExportToCsvState();
}

class _ExportToCsvState extends State<ExportToCsv> {
  bool isLoading = true;
  List<List<String>> itemList = [];
  Stream<QuerySnapshot> streamQuery =
      FirebaseFirestore.instance.collection('users').snapshots();

  @override
  void initState() {
    itemList = [
      <String>[
        'informations_status_status',
        'informations_status_progressValue',
        'informations_profile_name',
        'informations_profile_surname',
        'informations_profile_birth',
        'informations_profile_email',
        'informations_profile_mobile',
        'informations_profile_mobileDial',
        'informations_profile_gender',
        'informations_profile_nationality',
        'informations_profile_cityOfBirth',
        'informations_profile_countryOfBirth',
        'informations_profile_campusFrance',
        'informations_address_CP',
        'informations_address_street',
        'informations_address_city',
        'informations_address_comp',
        'informations_address_country',
        'informations_tutors_identical',
        'informations_tutors_CP',
        'informations_tutors_street',
        'informations_tutors_city',
        'informations_tutors_comp',
        'informations_tutors_country',
        'informations_comp_scholarship',
        'informations_comp_francophone',
        'informations_comp_MDPH',
        'informations_comp_sportsman',
        'informations_comp_language',
        'user_status_rgpd_accepted',
        'user_status_role',
        'user_status_accountCreatedAt',
        'user_statusFolder_isSubmitted',
        'user_statusFolder_status',
        'user_statusFolder_submittedAt',
        'user_statusFolder_modifiedAt',
        'user_statusFolder_modifiedBy',
        'cursus_isComplete',
        'cursus_programmeChoice',
        'cursus_yearChoice',
        'cursus_type',
        'cursus_spe',
        'cursus_status_status',
        'cursus_status_progressValue',
        'docComp_status_isComplete',
        'docComp_status_status',
        'docComp_status_progressValue',
        'docComp_id_card_path',
        'docComp_id_card_docNoExist',
        'docComp_id_card_explain',
        'docComp_id_card_bytes',
        'docComp_id_card_mimes',
        'docComp_id_card_name',
        'docComp_scholarship_path',
        'docComp_scholarship_docNoExist',
        'docComp_scholarship_explain',
        'docComp_scholarship_bytes',
        'docComp_scholarship_mimes',
        'docComp_scholarship_name',
        'docComp_cv_path',
        'docComp_cv_docNoExist',
        'docComp_cv_explain',
        'docComp_cv_bytes',
        'docComp_cv_mimes',
        'docComp_cv_name',
        'docComp_cover_letter_path',
        'docComp_cover_letter_docNoExist',
        'docComp_cover_letter_explain',
        'docComp_cover_letter_bytes',
        'docComp_cover_letter_mimes',
        'docComp_cover_letter_name',
        'docComp_en_test_path',
        'docComp_en_test_testWithSchool',
        'docComp_en_test_bytes',
        'docComp_en_test_mimes',
        'docComp_en_test_name',
        'docComp_fr_test_path',
        'docComp_fr_test_docNoExist',
        'docComp_fr_test_explain',
        'docComp_fr_test_bytes',
        'docComp_fr_test_mimes',
        'docComp_fr_test_name',
        'docComp_mdph_path',
        'docComp_mdph_docNoExist',
        'docComp_mdph_explain',
        'docComp_mdph_bytes',
        'docComp_mdph_mimes',
        'docComp_mdph_name',
        'docComp_sportman_path',
        'docComp_sportman_docNoExist',
        'docComp_sportman_explain',
        'docComp_sportman_bytes',
        'docComp_sportman_mimes',
        'docComp_sportman_name',
        'docComp_transcripts_first_final_path',
        'docComp_transcripts_first_final_docNoExist',
        'docComp_transcripts_first_final_explain',
        'docComp_transcripts_first_final_bytes',
        'docComp_transcripts_first_final_mimes',
        'docComp_transcripts_first_final_name',
        'docComp_transcripts_bacc_path',
        'docComp_transcripts_bacc_docNoExist',
        'docComp_transcripts_bacc_explain',
        'docComp_transcripts_bacc_bytes',
        'docComp_transcripts_bacc_mimes',
        'docComp_transcripts_bacc_name',
        'docComp_transcripts_note_supp_path',
        'docComp_transcripts_note_supp_docNoExist',
        'docComp_transcripts_note_supp_explain',
        'docComp_transcripts_note_supp_bytes',
        'docComp_transcripts_note_supp',
        'docComp_transcripts_note_supp',
        'docComp_recommandation_letter_path',
        'docComp_recommandation_letter_docNoExist',
        'docComp_recommandation_letter_explain',
        'docComp_recommandation_letter_bytes',
        'docComp_recommandation_letter_mimes',
        'docComp_recommandation_letter_name',
        'cursus_user_status_isComplete',
        'cursus_user_status_status',
        'cursus_user_status_progressValue',
        'cursus_user_2022-2023_years',
        'cursus_user_2022-2023_class',
        'cursus_user_2022-2023_school',
        'cursus_user_2022-2023_degrees',
        'cursus_user_2022-2023_city',
        'cursus_user_2022-2023_country',
        'cursus_user_2022-2023_explain',
        'cursus_user_2022-2023_isNotComplete',
        'cursus_user_2022-2023_statusCompleted',
        'cursus_user_2021-2022_years',
        'cursus_user_2021-2022_class',
        'cursus_user_2021-2022_school',
        'cursus_user_2021-2022_degrees',
        'cursus_user_2021-2022_city',
        'cursus_user_2021-2022_country',
        'cursus_user_2021-2022_explain',
        'cursus_user_2021-2022_isNotComplete',
        'cursus_user_2021-2022_statusCompleted',
        'cursus_user_2020-2021_years',
        'cursus_user_2020-2021_class',
        'cursus_user_2020-2021_school',
        'cursus_user_2020-2021_degrees',
        'cursus_user_2020-2021_city',
        'cursus_user_2020-2021_country',
        'cursus_user_2020-2021_explain',
        'cursus_user_2020-2021_isNotComplete',
        'cursus_user_2020-2021_statusCompleted',
        'cursus_user_2019-2020_years',
        'cursus_user_2019-2020_class',
        'cursus_user_2019-2020_school',
        'cursus_user_2019-2020_degrees',
        'cursus_user_2019-2020_city',
        'cursus_user_2019-2020_country',
        'cursus_user_2019-2020_explain',
        'cursus_user_2019-2020_isNotComplete',
        'cursus_user_2019-2020_statusCompleted',
        'payment_status_isComplete',
        'payment_status_status',
        'payment_status_progressValue',
        'payment_paymentCursus_paid',
        'payment_paymentCursus_path',
        'payment_paymentCursus_bytes',
        'payment_paymentCursus_mimes',
        'payment_paymentCursus_name',
        'payment_paymentCursus_docNoExist',
        'payment_paymentCursus_explain',
        'payment_paymentEasySpeaking_paid',
        'payment_paymentEasySpeaking_path',
        'payment_paymentEasySpeaking_bytes',
        'payment_paymentEasySpeaking_mimes',
        'payment_paymentEasySpeaking_name',
        'payment_paymentEasySpeaking_docNoExist',
        'payment_paymentEasySpeaking_explain',
        'payment_type_of_payment'
      ]
    ];
    isLoading = false;
    super.initState();
  }

  ScrollController _scrollControllerHorizontal = ScrollController();
  @override
  Widget build(BuildContext context) {
    return isLoading
        ? Loader()
        : Scaffold(
            appBar: AppBar(
              automaticallyImplyLeading: false,
              elevation: 0,
              backgroundColor: Colors.grey[100],
              centerTitle: true,
              title: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text("Données à exporter",
                      style: TextStyle(color: AppColors.primary)),
                  Row(
                    children: [
                      TextButton(
                        child: const Text('Fermer'),
                        onPressed: () {
                          navigator!.pop();
                        },
                      ),
                      const SizedBox(width: 10.0),
                      ElevatedButton.icon(
                          onPressed: () {
                            generateCsv();
                            navigator!.pop();
                          },
                          icon: const Icon(Icons.download),
                          label: const Text('Exporter')),
                    ],
                  ),
                ],
              ),
            ),
            backgroundColor: AppColors.bgColor,
            body: StreamBuilder<QuerySnapshot>(
              stream: streamQuery,
              builder: (context, snapshot) {
                if (!snapshot.hasData) {
                  return Loader();
                } else {
                  return Scrollbar(
                    thumbVisibility: true,
                    controller: _scrollControllerHorizontal,
                    child: SingleChildScrollView(
                      physics: const AlwaysScrollableScrollPhysics(),
                      controller: _scrollControllerHorizontal,
                      scrollDirection: Axis.horizontal,
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: <Widget>[
                          Container(
                            margin: const EdgeInsets.only(top: 10),
                            decoration: const BoxDecoration(
                                border: Border(
                              bottom: BorderSide(width: 1, color: Colors.grey),
                            )),
                            child: Row(
                                mainAxisAlignment: MainAxisAlignment.start,
                                children: [
                                  DataGridTitle(
                                    'informations_status_status',
                                  ),
                                  DataGridTitle(
                                    'informations_status_progressValue',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_name',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_surname',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_birth',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_email',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_mobile',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_mobileDial',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_gender',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_nationality',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_cityOfBirth',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_countryOfBirth',
                                  ),
                                  DataGridTitle(
                                    'informations_profile_campusFrance',
                                  ),
                                  DataGridTitle(
                                    'informations_address_CP',
                                  ),
                                  DataGridTitle(
                                    'informations_address_street',
                                  ),
                                  DataGridTitle(
                                    'informations_address_city',
                                  ),
                                  DataGridTitle(
                                    'informations_address_comp',
                                  ),
                                  DataGridTitle(
                                    'informations_address_country',
                                  ),
                                  DataGridTitle(
                                    'informations_tutors_identical',
                                  ),
                                  DataGridTitle(
                                    'informations_tutors_CP',
                                  ),
                                  DataGridTitle(
                                    'informations_tutors_street',
                                  ),
                                  DataGridTitle(
                                    'informations_tutors_city',
                                  ),
                                  DataGridTitle(
                                    'informations_tutors_comp',
                                  ),
                                  DataGridTitle(
                                    'informations_tutors_country',
                                  ),
                                  DataGridTitle(
                                    'informations_comp_scholarship',
                                  ),
                                  DataGridTitle(
                                    'informations_comp_francophone',
                                  ),
                                  DataGridTitle(
                                    'informations_comp_MDPH',
                                  ),
                                  DataGridTitle(
                                    'informations_comp_sportsman',
                                  ),
                                  DataGridTitle(
                                    'informations_comp_language',
                                  ),
                                  DataGridTitle(
                                    'user_status_rgpd_accepted',
                                  ),
                                  DataGridTitle(
                                    'user_status_role',
                                  ),
                                  DataGridTitle(
                                    'user_status_accountCreatedAt',
                                  ),
                                  DataGridTitle(
                                    'user_statusFolder_isSubmitted',
                                  ),
                                  DataGridTitle(
                                    'user_statusFolder_status',
                                  ),
                                  DataGridTitle(
                                    'user_statusFolder_submittedAt',
                                  ),
                                  DataGridTitle(
                                    'user_statusFolder_modifiedAt',
                                  ),
                                  DataGridTitle(
                                    'user_statusFolder_modifiedBy',
                                  ),
                                  DataGridTitle(
                                    'cursus_isComplete',
                                  ),
                                  DataGridTitle(
                                    'cursus_programmeChoice',
                                  ),
                                  DataGridTitle(
                                    'cursus_yearChoice',
                                  ),
                                  DataGridTitle(
                                    'cursus_type',
                                  ),
                                  DataGridTitle(
                                    'cursus_spe',
                                  ),
                                  DataGridTitle(
                                    'cursus_status_status',
                                  ),
                                  DataGridTitle(
                                    'cursus_status_progressValue',
                                  ),
                                  DataGridTitle(
                                    'docComp_status_isComplete',
                                  ),
                                  DataGridTitle(
                                    'docComp_status_status',
                                  ),
                                  DataGridTitle(
                                    'docComp_status_progressValue',
                                  ),
                                  DataGridTitle(
                                    'docComp_id_card_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_id_card_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_id_card_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_id_card_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_id_card_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_id_card_name',
                                  ),
                                  DataGridTitle(
                                    'docComp_scholarship_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_scholarship_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_scholarship_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_scholarship_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_scholarship_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_scholarship_name',
                                  ),
                                  DataGridTitle(
                                    'docComp_cv_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_cv_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_cv_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_cv_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_cv_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_cv_name',
                                  ),
                                  DataGridTitle(
                                    'docComp_cover_letter_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_cover_letter_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_cover_letter_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_cover_letter_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_cover_letter_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_cover_letter_name',
                                  ),
                                  DataGridTitle(
                                    'docComp_en_test_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_en_test_testWithSchool',
                                  ),
                                  DataGridTitle(
                                    'docComp_en_test_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_en_test_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_en_test_name',
                                  ),
                                  DataGridTitle(
                                    'docComp_fr_test_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_fr_test_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_fr_test_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_fr_test_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_fr_test_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_fr_test_name',
                                  ),
                                  DataGridTitle(
                                    'docComp_mdph_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_mdph_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_mdph_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_mdph_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_mdph_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_mdph_name',
                                  ),
                                  DataGridTitle(
                                    'docComp_sportman_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_sportman_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_sportman_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_sportman_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_sportman_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_sportman_name',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_first_final_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_first_final_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_first_final_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_first_final_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_first_final_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_first_final_name',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_bacc_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_bacc_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_bacc_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_bacc_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_bacc_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_bacc_name',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_note_supp_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_note_supp_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_note_supp_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_note_supp_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_note_supp',
                                  ),
                                  DataGridTitle(
                                    'docComp_transcripts_note_supp',
                                  ),
                                  DataGridTitle(
                                    'docComp_recommandation_letter_path',
                                  ),
                                  DataGridTitle(
                                    'docComp_recommandation_letter_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'docComp_recommandation_letter_explain',
                                  ),
                                  DataGridTitle(
                                    'docComp_recommandation_letter_bytes',
                                  ),
                                  DataGridTitle(
                                    'docComp_recommandation_letter_mimes',
                                  ),
                                  DataGridTitle(
                                    'docComp_recommandation_letter_name',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_status_isComplete',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_status_status',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_status_progressValue',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2022-2023_years',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2022-2023_class',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2022-2023_school',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2022-2023_degrees',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2022-2023_city',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2022-2023_country',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2022-2023_explain',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2022-2023_isNotComplete',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2022-2023_statusCompleted',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2021-2022_years',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2021-2022_class',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2021-2022_school',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2021-2022_degrees',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2021-2022_city',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2021-2022_country',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2021-2022_explain',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2021-2022_isNotComplete',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2021-2022_statusCompleted',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2020-2021_years',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2020-2021_class',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2020-2021_school',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2020-2021_degrees',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2020-2021_city',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2020-2021_country',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2020-2021_explain',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2020-2021_isNotComplete',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2020-2021_statusCompleted',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2019-2020_years',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2019-2020_class',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2019-2020_school',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2019-2020_degrees',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2019-2020_city',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2019-2020_country',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2019-2020_explain',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2019-2020_isNotComplete',
                                  ),
                                  DataGridTitle(
                                    'cursus_user_2019-2020_statusCompleted',
                                  ),
                                  DataGridTitle(
                                    'payment_status_isComplete',
                                  ),
                                  DataGridTitle(
                                    'payment_status_status',
                                  ),
                                  DataGridTitle(
                                    'payment_status_progressValue',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentCursus_paid',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentCursus_path',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentCursus_bytes',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentCursus_mimes',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentCursus_name',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentCursus_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentCursus_explain',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentEasySpeaking_paid',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentEasySpeaking_path',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentEasySpeaking_bytes',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentEasySpeaking_mimes',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentEasySpeaking_name',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentEasySpeaking_docNoExist',
                                  ),
                                  DataGridTitle(
                                    'payment_paymentEasySpeaking_explain',
                                  ),
                                  DataGridTitle('payment_type_of_payment')
                                ]),
                          ),
                          SizedBox(
                            width: 17500,
                            child: ListView.builder(
                              physics: ClampingScrollPhysics(),
                              shrinkWrap: true,
                              itemCount: snapshot.data!.docs.length,
                              itemBuilder: (context, index) {
                                DocumentSnapshot doc =
                                    snapshot.data!.docs[index];
                                itemList.add(<String>[
                                  (doc['informations']['status']['status'])
                                      .toString(),
                                  (doc['informations']['status']
                                          ['progressValue'])
                                      .toString(),
                                  doc['informations']['profile']['name'],
                                  doc['informations']['profile']['surname'],
                                  doc['informations']['profile']['birth'],
                                  doc['informations']['profile']['email'],
                                  doc['informations']['profile']['mobile'],
                                  doc['informations']['profile']['mobileDial'],
                                  doc['informations']['profile']['gender'],
                                  doc['informations']['profile']['nationality'],
                                  doc['informations']['profile']['cityOfBirth'],
                                  doc['informations']['profile']
                                      ['countryOfBirth'],
                                  doc['informations']['profile']
                                      ['campusFrance'],
                                  doc['informations']['address']['CP'],
                                  doc['informations']['address']['street'],
                                  doc['informations']['address']['city'],
                                  doc['informations']['address']['comp'],
                                  doc['informations']['address']['country'],
                                  (doc['informations']['tutors']['identical'])
                                      .toString(),
                                  doc['informations']['tutors']['CP'],
                                  doc['informations']['tutors']['street'],
                                  doc['informations']['tutors']['city'],
                                  doc['informations']['tutors']['comp'],
                                  doc['informations']['tutors']['country'],
                                  (doc['informations']['comp']['scholarship'])
                                      .toString(),
                                  (doc['informations']['comp']['francophone'])
                                      .toString(),
                                  (doc['informations']['comp']['MDPH'])
                                      .toString(),
                                  (doc['informations']['comp']['sportsman'])
                                      .toString(),
                                  doc['informations']['comp']['language'],
                                  (doc['user']['status']['rgpd_accepted'])
                                      .toString(),
                                  doc['user']['status']['role'],
                                  (doc['user']['status']['accountCreatedAt'])
                                      .toString(),
                                  (doc['user']['statusFolder']['isSubmitted'])
                                      .toString(),
                                  (doc['user']['statusFolder']['status'])
                                      .toString(),
                                  (doc['user']['statusFolder']['submittedAt'])
                                      .toString(),
                                  (doc['user']['statusFolder']['modifiedAt'])
                                      .toString(),
                                  doc['user']['statusFolder']['modifiedBy'],
                                  (doc['cursus']['isCompleted']).toString(),
                                  doc['cursus']['programmeChoice'],
                                  doc['cursus']['yearChoice'],
                                  doc['cursus']['type'],
                                  doc['cursus']['spe'],
                                  (doc['cursus']['status']['status'])
                                      .toString(),
                                  (doc['cursus']['status']['progressValue'])
                                      .toString(),
                                  (doc['docComp']['status']['isComplete'])
                                      .toString(),
                                  (doc['docComp']['status']['status'])
                                      .toString(),
                                  (doc['docComp']['status']['progressValue'])
                                      .toString(),
                                  doc['docComp']['id_card']['path'],
                                  (doc['docComp']['id_card']['docNoExist'])
                                      .toString(),
                                  doc['docComp']['id_card']['explain'],
                                  (doc['docComp']['id_card']['bytes'])
                                      .toString(),
                                  doc['docComp']['id_card']['mimes'],
                                  doc['docComp']['id_card']['name'],
                                  doc['docComp']['scholarship']['path'],
                                  (doc['docComp']['scholarship']['docNoExist'])
                                      .toString(),
                                  doc['docComp']['scholarship']['explain'],
                                  (doc['docComp']['scholarship']['bytes'])
                                      .toString(),
                                  doc['docComp']['scholarship']['mimes'],
                                  doc['docComp']['scholarship']['name'],
                                  doc['docComp']['cv']['path'],
                                  (doc['docComp']['cv']['docNoExist'])
                                      .toString(),
                                  doc['docComp']['cv']['explain'],
                                  (doc['docComp']['cv']['bytes']).toString(),
                                  doc['docComp']['cv']['mimes'],
                                  doc['docComp']['cv']['name'],
                                  doc['docComp']['cover_letter']['path'],
                                  (doc['docComp']['cover_letter']['docNoExist'])
                                      .toString(),
                                  doc['docComp']['cover_letter']['explain'],
                                  (doc['docComp']['cover_letter']['bytes'])
                                      .toString(),
                                  doc['docComp']['cover_letter']['mimes'],
                                  doc['docComp']['cover_letter']['name'],
                                  doc['docComp']['en_test']['path'],
                                  (doc['docComp']['en_test']['testWithSchool'])
                                      .toString(),
                                  (doc['docComp']['en_test']['bytes'])
                                      .toString(),
                                  doc['docComp']['en_test']['mimes'],
                                  doc['docComp']['en_test']['name'],
                                  doc['docComp']['fr_test']['path'],
                                  (doc['docComp']['fr_test']['docNoExist'])
                                      .toString(),
                                  doc['docComp']['fr_test']['explain'],
                                  (doc['docComp']['fr_test']['bytes'])
                                      .toString(),
                                  doc['docComp']['fr_test']['mimes'],
                                  doc['docComp']['fr_test']['name'],
                                  doc['docComp']['mdph']['path'],
                                  (doc['docComp']['mdph']['docNoExist'])
                                      .toString(),
                                  doc['docComp']['mdph']['explain'],
                                  (doc['docComp']['mdph']['bytes']).toString(),
                                  doc['docComp']['mdph']['mimes'],
                                  doc['docComp']['mdph']['name'],
                                  doc['docComp']['sportman']['path'],
                                  (doc['docComp']['sportman']['docNoExist'])
                                      .toString(),
                                  doc['docComp']['sportman']['explain'],
                                  (doc['docComp']['sportman']['bytes'])
                                      .toString(),
                                  doc['docComp']['sportman']['mimes'],
                                  doc['docComp']['sportman']['name'],
                                  doc['docComp']['transcripts_first_final']
                                      ['path'],
                                  (doc['docComp']['transcripts_first_final']
                                          ['docNoExist'])
                                      .toString(),
                                  doc['docComp']['transcripts_first_final']
                                      ['explain'],
                                  (doc['docComp']['transcripts_first_final']
                                          ['bytes'])
                                      .toString(),
                                  doc['docComp']['transcripts_first_final']
                                      ['mimes'],
                                  doc['docComp']['transcripts_first_final']
                                      ['name'],
                                  doc['docComp']['transcripts_bacc']['path'],
                                  (doc['docComp']['transcripts_bacc']
                                          ['docNoExist'])
                                      .toString(),
                                  doc['docComp']['transcripts_bacc']['explain'],
                                  (doc['docComp']['transcripts_bacc']['bytes'])
                                      .toString(),
                                  doc['docComp']['transcripts_bacc']['mimes'],
                                  doc['docComp']['transcripts_bacc']['name'],
                                  doc['docComp']['transcripts_note_supp']
                                      ['path'],
                                  (doc['docComp']['transcripts_note_supp']
                                          ['docNoExist'])
                                      .toString(),
                                  doc['docComp']['transcripts_note_supp']
                                      ['explain'],
                                  (doc['docComp']['transcripts_note_supp']
                                          ['bytes'])
                                      .toString(),
                                  doc['docComp']['transcripts_note_supp']
                                      ['mimes'],
                                  doc['docComp']['transcripts_note_supp']
                                      ['name'],
                                  doc['docComp']['recommandation_letter']
                                      ['path'],
                                  (doc['docComp']['recommandation_letter']
                                          ['docNoExist'])
                                      .toString(),
                                  doc['docComp']['recommandation_letter']
                                      ['explain'],
                                  (doc['docComp']['recommandation_letter']
                                          ['bytes'])
                                      .toString(),
                                  doc['docComp']['recommandation_letter']
                                      ['mimes'],
                                  doc['docComp']['recommandation_letter']
                                      ['name'],
                                  (doc['cursus_user']['status']['isComplete'])
                                      .toString(),
                                  (doc['cursus_user']['status']['status'])
                                      .toString(),
                                  (doc['cursus_user']['status']
                                          ['progressValue'])
                                      .toString(),
                                  doc['cursus_user']['2022-2023']['years'],
                                  doc['cursus_user']['2022-2023']['class'],
                                  doc['cursus_user']['2022-2023']['school'],
                                  doc['cursus_user']['2022-2023']['degrees'],
                                  doc['cursus_user']['2022-2023']['city'],
                                  doc['cursus_user']['2022-2023']['country'],
                                  doc['cursus_user']['2022-2023']['explain'],
                                  (doc['cursus_user']['2022-2023']
                                          ['isNotComplete'])
                                      .toString(),
                                  (doc['cursus_user']['2022-2023']
                                          ['statusCompleted'])
                                      .toString(),
                                  doc['cursus_user']['2021-2022']['years'],
                                  doc['cursus_user']['2021-2022']['class'],
                                  doc['cursus_user']['2021-2022']['school'],
                                  doc['cursus_user']['2021-2022']['degrees'],
                                  doc['cursus_user']['2021-2022']['city'],
                                  doc['cursus_user']['2021-2022']['country'],
                                  doc['cursus_user']['2021-2022']['explain'],
                                  (doc['cursus_user']['2021-2022']
                                          ['isNotComplete'])
                                      .toString(),
                                  (doc['cursus_user']['2021-2022']
                                          ['statusCompleted'])
                                      .toString(),
                                  doc['cursus_user']['2020-2021']['years'],
                                  doc['cursus_user']['2020-2021']['class'],
                                  doc['cursus_user']['2020-2021']['school'],
                                  doc['cursus_user']['2020-2021']['degrees'],
                                  doc['cursus_user']['2020-2021']['city'],
                                  doc['cursus_user']['2020-2021']['country'],
                                  doc['cursus_user']['2020-2021']['explain'],
                                  (doc['cursus_user']['2020-2021']
                                          ['isNotComplete'])
                                      .toString(),
                                  (doc['cursus_user']['2020-2021']
                                          ['statusCompleted'])
                                      .toString(),
                                  doc['cursus_user']['2019-2020']['years'],
                                  doc['cursus_user']['2019-2020']['class'],
                                  doc['cursus_user']['2019-2020']['school'],
                                  doc['cursus_user']['2019-2020']['degrees'],
                                  doc['cursus_user']['2019-2020']['city'],
                                  doc['cursus_user']['2019-2020']['country'],
                                  doc['cursus_user']['2019-2020']['explain'],
                                  (doc['cursus_user']['2019-2020']
                                          ['isNotComplete'])
                                      .toString(),
                                  (doc['cursus_user']['2019-2020']
                                          ['statusCompleted'])
                                      .toString(),
                                  (doc['payment']['status']['isComplete'])
                                      .toString(),
                                  (doc['payment']['status']['status'])
                                      .toString(),
                                  (doc['payment']['status']['progressValue'])
                                      .toString(),
                                  (doc['payment']['paymentCursus']['paid'])
                                      .toString(),
                                  doc['payment']['paymentCursus']['path'],
                                  (doc['payment']['paymentCursus']['bytes'])
                                      .toString(),
                                  doc['payment']['paymentCursus']['mimes'],
                                  doc['payment']['paymentCursus']['name'],
                                  (doc['payment']['paymentCursus']
                                          ['docNoExist'])
                                      .toString(),
                                  doc['payment']['paymentCursus']['explain'],
                                  (doc['payment']['paymentEasySpeaking']
                                          ['paid'])
                                      .toString(),
                                  doc['payment']['paymentEasySpeaking']['path'],
                                  (doc['payment']['paymentEasySpeaking']
                                          ['bytes'])
                                      .toString(),
                                  doc['payment']['paymentEasySpeaking']
                                      ['mimes'],
                                  doc['payment']['paymentEasySpeaking']['name'],
                                  (doc['payment']['paymentEasySpeaking']
                                          ['docNoExist'])
                                      .toString(),
                                  doc['payment']['paymentEasySpeaking']
                                      ['explain'],
                                  doc['payment']['type_of_payment']
                                ]);

                                return Container(
                                  margin: const EdgeInsets.only(bottom: 10),
                                  decoration: const BoxDecoration(
                                      border: Border(
                                    bottom: BorderSide(
                                        width: 1, color: Colors.grey),
                                  )),
                                  child: Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.start,
                                      crossAxisAlignment:
                                          CrossAxisAlignment.center,
                                      children: [
                                        DataGrid(
                                          doc['informations']['status']
                                                  ['status']
                                              .toString(),
                                        ),
                                        DataGrid((doc['informations']['status']
                                                ['progressValue'])
                                            .toString()),
                                        DataGrid(doc['informations']['profile']
                                            ['name']),
                                        DataGrid(doc['informations']['profile']
                                            ['surname']),
                                        DataGrid(doc['informations']['profile']
                                            ['birth']),
                                        DataGrid(doc['informations']['profile']
                                            ['email']),
                                        DataGrid(doc['informations']['profile']
                                            ['mobile']),
                                        DataGrid(doc['informations']['profile']
                                            ['mobileDial']),
                                        DataGrid(doc['informations']['profile']
                                            ['gender']),
                                        DataGrid(doc['informations']['profile']
                                            ['nationality']),
                                        DataGrid(doc['informations']['profile']
                                            ['cityOfBirth']),
                                        DataGrid(doc['informations']['profile']
                                            ['countryOfBirth']),
                                        DataGrid(doc['informations']['profile']
                                            ['campusFrance']),
                                        DataGrid(doc['informations']['address']
                                            ['CP']),
                                        DataGrid(doc['informations']['address']
                                            ['street']),
                                        DataGrid(doc['informations']['address']
                                            ['city']),
                                        DataGrid(doc['informations']['address']
                                            ['comp']),
                                        DataGrid(doc['informations']['address']
                                            ['country']),
                                        DataGrid((doc['informations']['tutors']
                                                ['identical'])
                                            .toString()),
                                        DataGrid(doc['informations']['tutors']
                                            ['CP']),
                                        DataGrid(doc['informations']['tutors']
                                            ['street']),
                                        DataGrid(doc['informations']['tutors']
                                            ['city']),
                                        DataGrid(doc['informations']['tutors']
                                            ['comp']),
                                        DataGrid(doc['informations']['tutors']
                                            ['country']),
                                        DataGrid((doc['informations']['comp']
                                                ['scholarship'])
                                            .toString()),
                                        DataGrid((doc['informations']['comp']
                                                ['francophone'])
                                            .toString()),
                                        DataGrid((doc['informations']['comp']
                                                ['MDPH'])
                                            .toString()),
                                        DataGrid((doc['informations']['comp']
                                                ['sportsman'])
                                            .toString()),
                                        DataGrid(doc['informations']['comp']
                                            ['language']),
                                        DataGrid((doc['user']['status']
                                                ['rgpd_accepted'])
                                            .toString()),
                                        DataGrid(doc['user']['status']['role']),
                                        DataGrid((doc['user']['status']
                                                ['accountCreatedAt'])
                                            .toString()),
                                        DataGrid((doc['user']['statusFolder']
                                                ['isSubmitted'])
                                            .toString()),
                                        DataGrid((doc['user']['statusFolder']
                                                ['status'])
                                            .toString()),
                                        DataGrid((doc['user']['statusFolder']
                                                ['submittedAt'])
                                            .toString()),
                                        DataGrid((doc['user']['statusFolder']
                                                ['modifiedAt'])
                                            .toString()),
                                        DataGrid(doc['user']['statusFolder']
                                            ['modifiedBy']),
                                        DataGrid((doc['cursus']['isCompleted'])
                                            .toString()),
                                        DataGrid(
                                            doc['cursus']['programmeChoice']),
                                        DataGrid(doc['cursus']['yearChoice']),
                                        DataGrid(doc['cursus']['type']),
                                        DataGrid(doc['cursus']['spe']),
                                        DataGrid((doc['cursus']['status']
                                                ['status'])
                                            .toString()),
                                        DataGrid((doc['cursus']['status']
                                                ['progressValue'])
                                            .toString()),
                                        DataGrid((doc['docComp']['status']
                                                ['isComplete'])
                                            .toString()),
                                        DataGrid((doc['docComp']['status']
                                                ['status'])
                                            .toString()),
                                        DataGrid((doc['docComp']['status']
                                                ['progressValue'])
                                            .toString()),
                                        DataGrid(
                                            doc['docComp']['id_card']['path']),
                                        DataGrid((doc['docComp']['id_card']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['docComp']['id_card']
                                            ['explain']),
                                        DataGrid((doc['docComp']['id_card']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(
                                            doc['docComp']['id_card']['mimes']),
                                        DataGrid(
                                            doc['docComp']['id_card']['name']),
                                        DataGrid(doc['docComp']['scholarship']
                                            ['path']),
                                        DataGrid((doc['docComp']['scholarship']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['docComp']['scholarship']
                                            ['explain']),
                                        DataGrid((doc['docComp']['scholarship']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(doc['docComp']['scholarship']
                                            ['mimes']),
                                        DataGrid(doc['docComp']['scholarship']
                                            ['name']),
                                        DataGrid(doc['docComp']['cv']['path']),
                                        DataGrid((doc['docComp']['cv']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(
                                            doc['docComp']['cv']['explain']),
                                        DataGrid((doc['docComp']['cv']['bytes'])
                                            .toString()),
                                        DataGrid(doc['docComp']['cv']['mimes']),
                                        DataGrid(doc['docComp']['cv']['name']),
                                        DataGrid(doc['docComp']['cover_letter']
                                            ['path']),
                                        DataGrid((doc['docComp']['cover_letter']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['docComp']['cover_letter']
                                            ['explain']),
                                        DataGrid((doc['docComp']['cover_letter']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(doc['docComp']['cover_letter']
                                            ['mimes']),
                                        DataGrid(doc['docComp']['cover_letter']
                                            ['name']),
                                        DataGrid(
                                            doc['docComp']['en_test']['path']),
                                        DataGrid((doc['docComp']['en_test']
                                                ['testWithSchool'])
                                            .toString()),
                                        DataGrid((doc['docComp']['en_test']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(
                                            doc['docComp']['en_test']['mimes']),
                                        DataGrid(
                                            doc['docComp']['en_test']['name']),
                                        DataGrid(
                                            doc['docComp']['fr_test']['path']),
                                        DataGrid((doc['docComp']['fr_test']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['docComp']['fr_test']
                                            ['explain']),
                                        DataGrid((doc['docComp']['fr_test']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(
                                            doc['docComp']['fr_test']['mimes']),
                                        DataGrid(
                                            doc['docComp']['fr_test']['name']),
                                        DataGrid(
                                            doc['docComp']['mdph']['path']),
                                        DataGrid((doc['docComp']['mdph']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(
                                            doc['docComp']['mdph']['explain']),
                                        DataGrid((doc['docComp']['mdph']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(
                                            doc['docComp']['mdph']['mimes']),
                                        DataGrid(
                                            doc['docComp']['mdph']['name']),
                                        DataGrid(
                                            doc['docComp']['sportman']['path']),
                                        DataGrid((doc['docComp']['sportman']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['docComp']['sportman']
                                            ['explain']),
                                        DataGrid((doc['docComp']['sportman']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(doc['docComp']['sportman']
                                            ['mimes']),
                                        DataGrid(
                                            doc['docComp']['sportman']['name']),
                                        DataGrid(doc['docComp']
                                                ['transcripts_first_final']
                                            ['path']),
                                        DataGrid((doc['docComp']
                                                    ['transcripts_first_final']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['docComp']
                                                ['transcripts_first_final']
                                            ['explain']),
                                        DataGrid((doc['docComp']
                                                    ['transcripts_first_final']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(doc['docComp']
                                                ['transcripts_first_final']
                                            ['mimes']),
                                        DataGrid(doc['docComp']
                                                ['transcripts_first_final']
                                            ['name']),
                                        DataGrid(doc['docComp']
                                            ['transcripts_bacc']['path']),
                                        DataGrid((doc['docComp']
                                                    ['transcripts_bacc']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['docComp']
                                            ['transcripts_bacc']['explain']),
                                        DataGrid((doc['docComp']
                                                ['transcripts_bacc']['bytes'])
                                            .toString()),
                                        DataGrid(doc['docComp']
                                            ['transcripts_bacc']['mimes']),
                                        DataGrid(doc['docComp']
                                            ['transcripts_bacc']['name']),
                                        DataGrid(doc['docComp']
                                            ['transcripts_note_supp']['path']),
                                        DataGrid((doc['docComp']
                                                    ['transcripts_note_supp']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['docComp']
                                                ['transcripts_note_supp']
                                            ['explain']),
                                        DataGrid((doc['docComp']
                                                    ['transcripts_note_supp']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(doc['docComp']
                                            ['transcripts_note_supp']['mimes']),
                                        DataGrid(
                                          doc['docComp']
                                              ['transcripts_note_supp']['name'],
                                        ),
                                        DataGrid(
                                          doc['docComp']
                                              ['recommandation_letter']['path'],
                                        ),
                                        DataGrid((doc['docComp']
                                                    ['recommandation_letter']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['docComp']
                                                ['recommandation_letter']
                                            ['explain']),
                                        DataGrid((doc['docComp']
                                                    ['recommandation_letter']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(doc['docComp']
                                            ['recommandation_letter']['mimes']),
                                        DataGrid(doc['docComp']
                                            ['recommandation_letter']['name']),
                                        DataGrid((doc['cursus_user']['status']
                                                ['isComplete'])
                                            .toString()),
                                        DataGrid((doc['cursus_user']['status']
                                                ['status'])
                                            .toString()),
                                        DataGrid((doc['cursus_user']['status']
                                                ['progressValue'])
                                            .toString()),
                                        DataGrid(doc['cursus_user']['2022-2023']
                                            ['years']),
                                        DataGrid(doc['cursus_user']['2022-2023']
                                            ['class']),
                                        DataGrid(doc['cursus_user']['2022-2023']
                                            ['school']),
                                        DataGrid(doc['cursus_user']['2022-2023']
                                            ['degrees']),
                                        DataGrid(doc['cursus_user']['2022-2023']
                                            ['city']),
                                        DataGrid(doc['cursus_user']['2022-2023']
                                            ['country']),
                                        DataGrid(doc['cursus_user']['2022-2023']
                                            ['explain']),
                                        DataGrid((doc['cursus_user']
                                                ['2022-2023']['isNotComplete'])
                                            .toString()),
                                        DataGrid((doc['cursus_user']
                                                    ['2022-2023']
                                                ['statusCompleted'])
                                            .toString()),
                                        DataGrid(doc['cursus_user']['2021-2022']
                                            ['years']),
                                        DataGrid(doc['cursus_user']['2021-2022']
                                            ['class']),
                                        DataGrid(doc['cursus_user']['2021-2022']
                                            ['school']),
                                        DataGrid(doc['cursus_user']['2021-2022']
                                            ['degrees']),
                                        DataGrid(doc['cursus_user']['2021-2022']
                                            ['city']),
                                        DataGrid(doc['cursus_user']['2021-2022']
                                            ['country']),
                                        DataGrid(doc['cursus_user']['2021-2022']
                                            ['explain']),
                                        DataGrid((doc['cursus_user']
                                                ['2021-2022']['isNotComplete'])
                                            .toString()),
                                        DataGrid((doc['cursus_user']
                                                    ['2021-2022']
                                                ['statusCompleted'])
                                            .toString()),
                                        DataGrid(doc['cursus_user']['2020-2021']
                                            ['years']),
                                        DataGrid(doc['cursus_user']['2020-2021']
                                            ['class']),
                                        DataGrid(doc['cursus_user']['2020-2021']
                                            ['school']),
                                        DataGrid(doc['cursus_user']['2020-2021']
                                            ['degrees']),
                                        DataGrid(doc['cursus_user']['2020-2021']
                                            ['city']),
                                        DataGrid(doc['cursus_user']['2020-2021']
                                            ['country']),
                                        DataGrid(doc['cursus_user']['2020-2021']
                                            ['explain']),
                                        DataGrid((doc['cursus_user']
                                                ['2020-2021']['isNotComplete'])
                                            .toString()),
                                        DataGrid((doc['cursus_user']
                                                    ['2020-2021']
                                                ['statusCompleted'])
                                            .toString()),
                                        DataGrid(doc['cursus_user']['2019-2020']
                                            ['years']),
                                        DataGrid(doc['cursus_user']['2019-2020']
                                            ['class']),
                                        DataGrid(doc['cursus_user']['2019-2020']
                                            ['school']),
                                        DataGrid(doc['cursus_user']['2019-2020']
                                            ['degrees']),
                                        DataGrid(doc['cursus_user']['2019-2020']
                                            ['city']),
                                        DataGrid(doc['cursus_user']['2019-2020']
                                            ['country']),
                                        DataGrid(doc['cursus_user']['2019-2020']
                                            ['explain']),
                                        DataGrid((doc['cursus_user']
                                                ['2019-2020']['isNotComplete'])
                                            .toString()),
                                        DataGrid((doc['cursus_user']
                                                    ['2019-2020']
                                                ['statusCompleted'])
                                            .toString()),
                                        DataGrid((doc['payment']['status']
                                                ['isComplete'])
                                            .toString()),
                                        DataGrid((doc['payment']['status']
                                                ['status'])
                                            .toString()),
                                        DataGrid((doc['payment']['status']
                                                ['progressValue'])
                                            .toString()),
                                        DataGrid((doc['payment']
                                                ['paymentCursus']['paid'])
                                            .toString()),
                                        DataGrid(doc['payment']['paymentCursus']
                                            ['path']),
                                        DataGrid((doc['payment']
                                                ['paymentCursus']['bytes'])
                                            .toString()),
                                        DataGrid(doc['payment']['paymentCursus']
                                            ['mimes']),
                                        DataGrid(doc['payment']['paymentCursus']
                                            ['name']),
                                        DataGrid((doc['payment']
                                                ['paymentCursus']['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['payment']['paymentCursus']
                                            ['explain']),
                                        DataGrid((doc['payment']
                                                ['paymentEasySpeaking']['paid'])
                                            .toString()),
                                        DataGrid(doc['payment']
                                            ['paymentEasySpeaking']['path']),
                                        DataGrid((doc['payment']
                                                    ['paymentEasySpeaking']
                                                ['bytes'])
                                            .toString()),
                                        DataGrid(doc['payment']
                                            ['paymentEasySpeaking']['mimes']),
                                        DataGrid(doc['payment']
                                            ['paymentEasySpeaking']['name']),
                                        DataGrid((doc['payment']
                                                    ['paymentEasySpeaking']
                                                ['docNoExist'])
                                            .toString()),
                                        DataGrid(doc['payment']
                                            ['paymentEasySpeaking']['explain']),
                                        DataGrid(
                                            doc['payment']['type_of_payment']),
                                      ]),
                                );
                              },
                            ),
                          )
                        ],
                      ),
                    ),
                  );
                }
              },
            ));
  }

  Widget DataGrid(String str) {
    return Container(
      width: 100,
      child: Text(
        str,
        overflow: TextOverflow.ellipsis,
      ),
    );
  }

  Widget DataGridTitle(String str) {
    return Container(
      width: 100,
      child: Tooltip(
        message: str,
        waitDuration: const Duration(milliseconds: 300),
        child: Text(
          str,
          style: Theme.of(context).textTheme.bodyText2,
          overflow: TextOverflow.ellipsis,
        ),
      ),
    );
  }

  generateCsv() async {
    String csvdata = ListToCsvConverter().convert(itemList);

    final date = DateTime.now();

    final bytes = utf8.encode(csvdata);

    final blob = html.Blob([bytes]);

    final url = html.Url.createObjectUrlFromBlob(blob);

    final anchor = html.document.createElement("a") as html.AnchorElement
      ..href = url
      ..style.display = 'none'
      ..download = "item_export_$date.csv";

    html.document.body!.children.add(anchor);

    anchor.click();

    html.Url.revokeObjectUrl(url);
  }
}
